# Aknur Mansurkhan

## 1-БӨЛІМ: Сериялар (Series) және Деректер Фреймдерін (DataFrame) Құру

### Тапсырма 1: Pandas импорты және Series құру

Pandas кітапханасын импорттаңыз және 5 элементтен тұратын (мысалы, қала атаулары) индексі жоқ қарапайым Pandas Series құрыңыз. Серияны басып шығарыңыз.

In [1]:
import pandas as pd

In [2]:
qalalar=pd.Series(['Shymkent', 'Almaty', 'Astana', 'Aqtobe', 'Taraz'])

In [3]:
qalalar

0    Shymkent
1      Almaty
2      Astana
3      Aqtobe
4       Taraz
dtype: object

### Тапсырма 2: DataFrame құру

Келесі деректерді пайдаланып DataFrame құрыңыз:
* **Атауы (Name)**: ['Әли', 'Мәдина', 'Қайрат', 'Айгүл']
* **Жасы (Age)**: [25, 30, 22, 35]
* **Қаласы (City)**: ['A', 'B', 'A', 'C']

DataFrame-ді `df` айнымалысына сақтап, оны басып шығарыңыз.

In [4]:
df=pd.DataFrame({'Name':['Әли', 'Мәдина', 'Қайрат', 'Айгүл'],'Age': [25, 30, 22, 35], 'City':['A', 'B', 'A', 'C']})

In [5]:
df

     Name  Age City
0     Әли   25    A
1  Мәдина   30    B
2  Қайрат   22    A
3   Айгүл   35    C

## 2-БӨЛІМ: Индексациялау, Таңдау және Шарт бойынша Сүзу

### Тапсырма 3: Бір бағанды таңдау

`df` DataFrame-нен тек **'Name'** бағанын таңдап, оны басып шығарыңыз. Нәтиже Series болуы керек.

In [6]:
df['Name']

0       Әли
1    Мәдина
2    Қайрат
3     Айгүл
Name: Name, dtype: object

### Тапсырма 4: loc арқылы жолдар мен бағандарды таңдау
`df` DataFrame-нен **тек 'Age' және 'City' бағандарын** таңдап, **тек бірінші және үшінші жолдарды** (0 және 2 индекс) шығарыңыз. `loc` әдісін қолданыңыз.

In [7]:
df.loc[0:2:2,['Age', 'City']]

   Age City
0   25    A
2   22    A

### Тапсырма 5: iloc арқылы таңдау

`df` DataFrame-нен **барлық жолдарды** және **екінші және үшінші бағандарды** (1 және 2 индекс) шығарыңыз. `iloc` әдісін қолданыңыз.

In [9]:
df.iloc[:,[1,2]]

   Age City
0   25    A
1   30    B
2   22    A
3   35    C

### Тапсырма 6: Шарт бойынша сүзу

`df` DataFrame-нен жасы **25-тен үлкен** (`Age > 25`) барлық адамдарды сүзіңіз. Нәтижені басып шығарыңыз.

In [8]:
df[df['Age']>25]

     Name  Age City
1  Мәдина   30    B
3   Айгүл   35    C

### Тапсырма 7: Күрделі шарт бойынша сүзу

`df` DataFrame-нен **'City' бағаны 'A' немесе 'City' бағаны 'B' және 'Age' бағаны 30-ға тең** (`City == 'A'` немесе (`City == 'B'` және `Age == 30`)) болатын барлық жолдарды сүзіңіз.

In [11]:
df[(df['City'] == 'A') | ((df['City'] == 'B') & (df['Age'] == 30))]

     Name  Age City
0     Әли   25    A
1  Мәдина   30    B
2  Қайрат   22    A

## 3-БӨЛІМ: Топтастыру (groupby) және Агрегаттау

### Тапсырма 8: Жаңа DataFrame дайындау

Келесі деректерден жаңа `sales_df` DataFrame-ін жасаңыз:
* **Өнім (Product)**: ['A', 'B', 'A', 'C', 'B', 'C']
* **Аймақ (Region)**: ['Солтүстік', 'Оңтүстік', 'Оңтүстік', 'Солтүстік', 'Солтүстік', 'Оңтүстік']
* **Сатылымдар (Sales)**: [100, 150, 120, 80, 200, 90]

In [12]:
sales_df =pd.DataFrame({'Product':['A', 'B', 'A', 'C', 'B', 'C'],
                        'Region': ['Солтүстік', 'Оңтүстік', 'Оңтүстік', 'Солтүстік', 'Солтүстік', 'Оңтүстік'],
                        'Sales': [100, 150, 120, 80, 200, 90]
                        })

### Тапсырма 9: Бір баған бойынша топтастыру және қосынды

`sales_df` DataFrame-дегі **'Product'** бойынша топтастырыңыз және әр өнімнің **жалпы сатылымын** (қосындысын) есептеңіз. Нәтижені басып шығарыңыз.

In [13]:
sales_df.groupby('Product')['Sales'].sum()

Product
A    220
B    350
C    170
Name: Sales, dtype: int64

### Тапсырма 10: Көп баған бойынша топтастыру және орташа мән

`sales_df` DataFrame-дегі **'Product' және 'Region'** бойынша топтастырыңыз және әр комбинация үшін **орташа сатылымды** есептеңіз. Нәтижені басып шығарыңыз.

In [14]:
sales_df.groupby(['Product', 'Region'])['Sales'].mean()

Product  Region
A        Оңтүстік     120.0
         Солтүстік    100.0
B        Оңтүстік     150.0
         Солтүстік    200.0
C        Оңтүстік      90.0
         Солтүстік     80.0
Name: Sales, dtype: float64

### Тапсырма 11: Бірнеше агрегаттық функция

`sales_df` DataFrame-дегі **'Region'** бойынша топтастырыңыз және әр аймақ үшін **жалпы сатылымдарды (sum), сатылымдардың орташа мәнін (mean)** және **сатылымдардың ең көп санын (max)** есептеңіз. `agg` әдісін қолданыңыз.

In [15]:
sales_df.groupby('Region')['Sales'].agg(['sum', 'mean','max'])

           sum        mean  max
Region
Оңтүстік   360  120.000000  150
Солтүстік  380  126.666667  200

## 4-БӨЛІМ: Кестелерді Біріктіру (Merge, Join, Concat)

### Тапсырма 13: Жаңа DataFrame-лер дайындау

Біріктіру үшін екі жаңа DataFrame құрыңыз:

1.  `df1` (Пайдаланушы ақпараты):
    * **id**: [1, 2, 3, 4]
    * **Name**: ['Аян', 'Бек', 'Сара', 'Дәурен']
2.  `df2` (Тапсырыс ақпараты):
    * **user_id**: [2, 1, 4, 5, 3]
    * **Order**: ['Өнім X', 'Өнім Y', 'Өнім Z', 'Өнім V', 'Өнім W']

In [16]:
df1=pd.DataFrame({'id':[1, 2, 3, 4] , 'Name':  ['Аян', 'Бек', 'Сара', 'Дәурен']})
df2=pd.DataFrame({'user_id':[2, 1, 4,5,3], 'Order':  ['Өнім X', 'Өнім Y', 'Өнім Z', 'Өнім V', 'Өнім W']})

### Тапсырма 14: Ішкі біріктіру (Inner Merge)

`df1` мен `df2` DataFrame-лерін **ішкі біріктіру (inner merge)** арқылы біріктіріңіз. Біріктіру кілті ретінде `df1`-дегі **'id'** және `df2`-дегі **'user_id'** бағандарын пайдаланыңыз. Тек екі кестеде де бар пайдаланушылардың деректері қалуы керек.

In [17]:
inner=pd.merge(df1, df2, left_on='id', right_on='user_id')
inner

   id    Name  user_id   Order
0   1     Аян        1  Өнім Y
1   2     Бек        2  Өнім X
2   3    Сара        3  Өнім W
3   4  Дәурен        4  Өнім Z

### Тапсырма 15: Сол жақтан біріктіру (Left Merge)

`df1` мен `df2` DataFrame-лерін **сол жақтан біріктіру (left merge)** арқылы біріктіріңіз. Барлық пайдаланушылардың деректері (`df1`) сақталуы керек, ал сәйкес тапсырысы жоқтар үшін NaN мәні қойылуы керек.

In [18]:
sol=pd.merge(df1, df2, how='left', left_on='id', right_on='user_id')
sol

   id    Name  user_id   Order
0   1     Аян        1  Өнім Y
1   2     Бек        2  Өнім X
2   3    Сара        3  Өнім W
3   4  Дәурен        4  Өнім Z

### Тапсырма 16: Толық біріктіру (Outer Merge)

`df1` мен `df2` DataFrame-лерін **толық біріктіру (outer merge)** арқылы біріктіріңіз. Екі кестедегі барлық деректер сақталуы керек. Сәйкес келмейтін жерлер NaN-мен толтырылуы керек.

In [20]:
tolyq=pd.merge(df1, df2, how='outer',left_on='id', right_on='user_id')
tolyq

    id    Name  user_id   Order
0  1.0     Аян        1  Өнім Y
1  2.0     Бек        2  Өнім X
2  3.0    Сара        3  Өнім W
3  4.0  Дәурен        4  Өнім Z
4  NaN     NaN        5  Өнім V

### Тапсырма 17: Concat арқылы біріктіру

Жаңа `df3` DataFrame-ін құрыңыз:
* **id**: [5, 6]
* **Name**: ['Марат', 'Назира']
Содан кейін `pd.concat` әдісін қолданып, `df1` мен `df3`-ті **жолдар бойынша** біріктіріңіз.

In [21]:
df3=pd.DataFrame({'id':[5, 6] , 'Name':  ['Марат', 'Назира']})

In [23]:
pd.concat([df1, df3])

   id    Name
0   1     Аян
1   2     Бек
2   3    Сара
3   4  Дәурен
0   5   Марат
1   6  Назира

## 5-БӨЛІМ: Аралас және Қиын Тапсырмалар

### Тапсырма 18: Жаңа бағанды есептеу және сүзу

Бастапқы `df` DataFrame-іне келесі деректерді қосыңыз:
* **Salary**: [50000, 60000, 45000, 70000]
Жаңа **'Bonus'** бағанын есептеңіз, ол **'Salary' бағанының 10%** құрайды. Содан кейін тек **'Salary' 50000-нан жоғары** адамдарды таңдаңыз.

In [24]:
df['Salary']=[50000, 60000, 45000, 70000]
df['Bonus']=df['Salary'] * 0.10

In [26]:
df[df['Salary']>50000]

     Name  Age City  Salary   Bonus
1  Мәдина   30    B   60000  6000.0
3   Айгүл   35    C   70000  7000.0

### Тапсырма 19: Көп сатылы агрегаттау және сүзу
`sales_df` DataFrame-дегі **'Region'** бойынша топтастырыңыз. Тек **орташа сатылымы 100-ден жоғары** (`mean() > 100`) аймақтарды ғана таңдап, олардың жалпы сатылымын (sum) көрсетіңіз. `groupby().filter()` немесе `groupby().agg()` және сүзуді қолданыңыз.

In [34]:
sales_df.groupby('Region').filter(lambda x: x['Sales'].mean() > 100)

  Product     Region  Sales
0       A  Солтүстік    100
1       B   Оңтүстік    150
2       A   Оңтүстік    120
3       C  Солтүстік     80
4       B  Солтүстік    200
5       C   Оңтүстік     90

In [32]:
regional_sales_summary = sales_df.groupby('Region')['Sales'].agg(['mean', 'sum'])
filtered_summary = regional_sales_summary[regional_sales_summary['mean'] > 100]
filtered_summary['sum']

Region
Оңтүстік     360
Солтүстік    380
Name: sum, dtype: int64